name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest


    steps:

    - name: Check out code
      uses: actions/checkout@v2
      env:
       message: ${{ github.event.head_commit.message }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_JAEMOO }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JAEMOO }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         ECR_REPOSITORY: hengsgg
#         IMAGE_TAG: latest
      run: |
        docker build -t project-team-i-deploy .
        docker tag project-team-i-deploy:latest 765851371674.dkr.ecr.ap-northeast-2.amazonaws.com/project-team-i-deploy:latest
        docker push 765851371674.dkr.ecr.ap-northeast-2.amazonaws.com/project-team-i-deploy:latest
